### ISSUE TITLE
Error when adding Heading or Pictures

### ISSUE THREAD

**Issue by garthh** [humhub/wiki#100]
Hi, I use Humhub for 2 years, but, when a Heading or a Picture is added to a wiki page, the page cannot be displayed.

![image](https://user-images.githubusercontent.com/1765394/64077420-c6146500-ccd0-11e9-9ce7-bc452e77996b.png)

In the database, the code of this page is correct.

Thank you !

**Comment by buddh4** [comment]
Sorry for the late reply can you check the javascript console  of your browser for any errors?
