### ISSUE TITLE
[Enhancement] New features for Toolbar

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/wiki#115]
### Introduction

As we just set up an own instance of Etherpad Lite we were pretty suprised, how many stable Plugins it offers. [Sandstorm](https://alpha.sandstorm.io/grain) provides an one hour test version to play around with some of those mentioned plugins. This motivated us, to make up our minds and dream of new toolbar features for the HumHub wiki.

![image](https://user-images.githubusercontent.com/44228345/78354245-d1ec4080-75ab-11ea-83c9-1cf4ef56404e.png)

### Feature proposal/Possible solution

Being more precise, our group thinks, that the following features could be useful 

- Print/View as PDF/ODT, page width should be constant (optional: toggle page breaks on and off)
- align options (group style/justification)
- Underline
- Font Size
- Text Color
- Font Family
- Subscript/ Superscript

We don't want to overfill the toolbar, these features could be somehow hidden as we see here

![image](https://user-images.githubusercontent.com/44228345/78354560-6191ef00-75ac-11ea-9552-11300fe7e35e.png) 
↓
![image](https://user-images.githubusercontent.com/44228345/78354590-6e164780-75ac-11ea-9aed-750cfd3ac733.png) 

or they could be grouped in menus as you already do with upload, image and hr line. ![image](https://user-images.githubusercontent.com/44228345/78354820-dc5b0a00-75ac-11ea-8bb6-f30eaff5e62d.png)

This could e.g. be applied for the align options.

Furthermore we dream of build in (even though I guess this exceeds the limits of the editor and yes we know, there is the option to use the Etherpad module): 

- comments
- authorship (at least within the page history to see who exactly changed what)
- toggle markdown as an option to WYSIWYG

### Question

Have you already thought of introducing some of the proposed features? What is your opinion about them? I would be glad discussing that with you!

All this probably sounds really ambitious, but it would really help to create even better and prettier wiki pages as they are already now! 

At this point thank you really much for the work you're doing here and for all the improvements you've already done, this is top level!

**Comment by devcline** [comment]
Voting UP!

**Comment by buddh4** [comment]
Thanks for the feedback!

The main problem is that pure markdown is rather limited, we'd need to allow more html for most of the mentioned features (at least the formatting). There are markdown extensions available for some features as math formulars etc. but adding too much non standard markdown syntax somehow eliminates the benifits of using a markdown format.

I think in contrast to word or etherpad documents, wiki pages should follow a specific format, so I don't see the need for too much styling options as for example font-family and size.

Following mentioned features indeed would be very useful:

- Additional format options as subscript/suberscript/underline which may even could be added to the default richtext (comments/posts), but unfortunatley are not markdown standard.
- Print/export feature would be great
- Generally improving collaboration capabilities

Another solution would be allowing to switch the wiki editor by module or even allowing different types of pages similiar to the custom pages module.

We'll probably rework the wiki soon and will consider and discuss your feature requests.

**Comment by Oremountainflorian** [comment]
Thanks for your comprehensive reply! As you already pointed out, I also think **print/export** (with fixed page width as its seen in the editor) and improved **collaboration** are the most gainful and game-changing features. :) 

Nevertheless https://github.com/humhub/humhub-modules-wiki/issues/113 and https://github.com/humhub/humhub-modules-wiki/issues/114 seem also important to me. 

Indeed, the other features like underline and font color (for my part I consider these two more important than font size/family and sub/-superscripts) are rather nice to haves with clearly lower priority. 

@buddh4 Just one additional question: Have you (and your team) already thought of allowing the publication of single wiki pages without any further access (even if guests aren't enabled)? Or does this break with your/HumHubs concept? Same question applies for documents in the files module. This would significantly help us working together with other groups. 

My community and I are longingly looking forward to a reworked wiki with new helpful features! Thank you very much for your work and your efforts! King regards, Florian

**Comment by buddh4** [comment]
Some modules as for example the onlyoffice module allows generating an share link for sharing documents with non members (even with disabled guest mode) we should think of a generic way of creating share links for other content types. But yes, its possible, perhaps create a seperate feature request for this.
