### ISSUE TITLE
[Enhancement] Collaborate Feature in ParseMirror

### ISSUE THREAD

**Issue by warshell** [humhub/wiki#121]
Can we add a [collaborate feature](https://prosemirror.net/examples/collab/#edit-Example) to the parsemirror?

**Comment by Oremountainflorian** [comment]
@devcline I guess you mean ProseMirror? ;) 

The topic with collaborative editing was already touched in issue https://github.com/humhub/humhub-modules-wiki/issues/63

Are there novel efforts towards this?

**Comment by devcline** [comment]
Im sorry haha "deja vue" in my head. and yes its ProseMirror :D
