### ISSUE TITLE
[Minor Bug] Broken mentionings in stream

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/wiki#126]
## Problem description 

Preview of wiki pages with two mentionings at the beginning in the stream is broken under certain circumstances (one mentioning works fine).

## Steps to reproduce

OS: Win 8.1
Browser: Firefox 75
Version: HumHub 1.5.1

- Create a wiki page
- Write 4 lines (doesn't matter whether separated by enter or not)
- Put two mentionings to the 5th line (it doesn't matter if it's inside a heading or normal text)
- Behaviour in the stream: The second mentioning is broken

### <ins>↓Wiki↓</ins>
![grafik](https://user-images.githubusercontent.com/44228345/80676180-80ee4000-8ab6-11ea-9055-d15fcd9f9273.png)

### <ins>↓Stream↓</ins>
![grafik](https://user-images.githubusercontent.com/44228345/80676092-4e444780-8ab6-11ea-8bbf-02a96b560229.png)

### <ins>↓Stream (problem doesn't occur with <4 lines above)↓</ins>
![grafik](https://user-images.githubusercontent.com/44228345/80676255-abd89400-8ab6-11ea-8519-f7f77e885418.png)

**Comment by buddh4** [comment]
Added to: https://github.com/humhub/humhub/issues/4215 thanks for reporting.
