### ISSUE TITLE
An internal server error occurred.

### ISSUE THREAD

**Issue by matzter** [humhub/wiki#137]
I get this error on my installation when trying to create a new page.
The humhub community, latest version runs on Siteground. 

Support said:

> 
> Upon tracing the process live, it is accessing a high number of files at once which reaches the said limit.
> 
>      0.000054 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4c.cfs", O_RDWR) = 43
>      0.000050 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4c.cfs", O_RDWR) = 44
>      0.000051 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4c.cfs", O_RDWR) = 45
>      0.000053 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4d.cfs", O_RDWR) = 46
>      0.000058 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4d.cfs", O_RDWR) = 47
>      0.000048 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4d.cfs", O_RDWR) = 48
>      0.000059 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4e.cfs", O_RDWR) = 49
>      0.000043 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4e.cfs", O_RDWR) = 50
>      0.000041 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4e.cfs", O_RDWR) = 51
>      0.000126 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4f.cfs", O_RDWR) = 52
>      0.000050 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4f.cfs", O_RDWR) = 53
>      0.000044 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4f.cfs", O_RDWR) = 54
>      0.000053 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4g.cfs", O_RDWR) = 55
>      0.000050 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4g.cfs", O_RDWR) = 56
>      0.000047 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4g.cfs", O_RDWR) = 57
>      0.000047 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4h.cfs", O_RDWR) = 58
>      0.000038 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4h.cfs", O_RDWR) = 59
>      0.000040 open("/home/xyz/public_html/xyz/protected/runtime/searchdb/_4h.cfs", O_RDWR) = -1 EMFILE (Too many open files)

**Comment by luke-** [comment]
Can you please try to rebuild the search index? 
https://docs.humhub.org/docs/admin/troubleshooting#search-index

But it looks like your shared hoster uses limits that are too low for HumHub.

**Comment by StevenAJC** [comment]
Another user here with a new install of HumHub 1.7.1, running on Siteground, and with the Wiki 1.4.2 module enabled. It's a test installation with only 4 users, 5 spaces, and the Wiki only has 6 articles.

Also generating the "An internal server error occurred" when creating a new Wiki entry or if successful in creating one, when edit it.  

If some hosting services limit the number of open files surely there must be a problem somewhere in HumHub or Wiki if that file open limit is being reached on such a small configuration? (I.e. Can this scale?  E.g. if have more content and users even when installed on a larger hosted platform will this same issue arise but with another, albeit higher, file open limit being rapidly consumed?)

Have rebuilt search index, running HumHub 1.7.1, and `php -v` reports:
`PHP 7.3.25 (cli) (built: Dec  4 2020 08:09:57) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.4, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies`

Is this overly excessive use of file opens a Wiki module issue, or is it showing here as a result of something else in HumHub? E.g. have seen 'zendsearch' throw up file open errors as well. 

Any help to resolve or work around this problem would be appreciated please.

**Comment by luke-** [comment]
@StevenAJC The number of open files refers to HumHub as an application and has nothing to do with scaling or the number of users/contents.There is no other option but to increase the limit if you want to use HumHub.

**Comment by StevenAJC** [comment]
Hello @luke-, thank you for the prompt response. Just to confirm therefore that an otherwise "empty" HumHub installation needs to be able to have over 1000 open files at any one point in time and that this isn't some form of bug with files not being closed / promptly closed when they're no longer required?

**Comment by luke-** [comment]
No, it's not a bug.

**Comment by StevenAJC** [comment]
Okay thank you.

**Comment by StevenAJC** [comment]
Siteground support have advised that they have a limit of files opened by a single process as being 60 - just checking if this sounds reasonable for a HumHub installation?
