### ISSUE TITLE
Add save to sidebar navigation.

### ISSUE THREAD

**Issue by buddh4** [humhub/wiki#138]
On longer pages the save button at the bottom of the page is a bit hidden. Also other features like delete are present in the sidebar which is a bit confusing.

**Comment by yurabakhtin** [comment]
@luke- Do you know what means here "a bit hidden"? Is it hidden and impossible to press the button?
I can see the button "Save" when scroll down on longer pages, i.e. it is possible to press on the button.
Or should we add new link like this:
<img width="1067" alt="save" src="https://user-images.githubusercontent.com/6995524/123069597-97bec700-d41b-11eb-92fc-be8aa1b4afd5.png">

**Comment by luke-** [comment]
@yurabakhtin Yes, it would be good if we could have an additional Save button here. There will probably be another major redesign here later.

**Comment by yurabakhtin** [comment]
@luke- Ok, PR https://github.com/humhub/wiki/pull/185:
<img width="958" alt="sidebar_save_action" src="https://user-images.githubusercontent.com/6995524/123091722-5a196880-d432-11eb-97a0-3fcfd61bf47d.png">

**Comment by luke-** [comment]
@yurabakhtin Can you please put "Save" on the first position. Maybe some more prominent?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please put "Save" on the first position.

Commit https://github.com/humhub/wiki/pull/185/commits/9c9f049695ff985340890abfe043fc3cf661e166

> Maybe some more prominent?

Commit https://github.com/humhub/wiki/pull/185/commits/4daa940085606e1cc162c573bd8ef95f5415948f:

<img width="962" alt="save_btn_position" src="https://user-images.githubusercontent.com/6995524/123951694-bee23f00-d9ad-11eb-8b33-2b5a9311593d.png">

**Comment by luke-** [comment]
@yurabakhtin thanks!
