### ISSUE TITLE
Expand category hierarchy

### ISSUE THREAD

**Issue by JK742020** [humhub/wiki#140]
Found an issue from 2018. https://github.com/humhub/humhub-modules-wiki/issues/66

Still it would be really great to have more levels. 

For example: 
Books/Birds/page 1, page 2, ...
Books/Mammals/page 1, page 2, ...

**Comment by arnebader** [comment]
Yes, this would be great!

**Comment by akorsonsky** [comment]
yes it'll be a great update

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/190

<img width="956" alt="page_list" src="https://user-images.githubusercontent.com/6995524/125096626-00759700-e0de-11eb-9b90-e1f81464c229.png">

I didn't find a way to use spaces before sub categories title inside `<option>`, so I made this with chars `-`:
(CSS propertries `padding-left`, `margin-left`, `text-indent` don't work there)
<img width="956" alt="edit_cat" src="https://user-images.githubusercontent.com/6995524/125096632-02d7f100-e0de-11eb-9d8b-fc7a5ed584cf.png">

**Comment by luke-** [comment]
@yurabakhtin Looks very good! The solution with the dashes is ok. Possibly we will use a Select2 here in the future.
