### ISSUE TITLE
not "move content" only but move/copy content

### ISSUE THREAD

**Issue by JK742020** [humhub/wiki#141]
It would be helpful to not only move a page from the wiki but copy it.

Just offer the possibility to set a hook (copy) before choosing the target-space.

**Comment by buddh4** [comment]
So changes to one wiki will also affect the cloned one?

**Comment by JK742020** [comment]
Good Question. I think there wan't be any changes because the work is finished bevor cloning. But to keep this in mind it could be like this. Cloning means making a copy and if there are any changes made with the copy that's fine and it will not effect the original one.

**Comment by buddh4** [comment]
I think it would be better to mark content as draft and hide them for non admin/moderators until they are finished, this would then work for all content types.

**Comment by JK742020** [comment]
and how to realise the issue with copy content? 
I think it is a good idea to implement move/copy for all content types as well.
