### ISSUE TITLE
Wiki gets stuck when saving

### ISSUE THREAD

**Issue by JK742020** [humhub/wiki#146]
Sometimes when placing a photo into the text area the dots show up to indicate that there is some saving in the background. That's the same when saving the whole wiki. 

Sometimes the dots show up and nothing else happens. You can wait for a while, nothing happens. Dots moving only.

In this situation I click something else and come back to the wiki to try again. One time two times and, no idea why, it works.

Any ideas?

**Comment by buddh4** [comment]
Maybe check the developer console of your browser the next time this happens and also the backend logs.

**Comment by JK742020** [comment]
ok. thanks.

**Comment by buddh4** [comment]
I'll add this to the richtext overview issue just to do some further investigation. Usually in case of an error the loader should stop.
