### ISSUE TITLE
Export/Import Wiki

### ISSUE THREAD

**Issue by gerhardbeck** [humhub/wiki#152]
Hi, I'd love to see an export/import function of wiki pages or a wiki itself.

Why? It would be great in order to copy a wiki or some pages to another humhub installation. Usefull e.g. for a wiki with explanations how humhub works.

**Comment by luke-** [comment]
@gerhardbeck Exclusively for the wiki module we do not plan this functionality. In the longer term, however, something like this would be interesting for HumHub in general, regardless of the content type.
