### ISSUE TITLE
On a mobile device, can't change the page order by Drag&Drop on the Wiki index page

### ISSUE THREAD

**Issue by sakurafarm** [humhub/wiki#155]
I created a few test pages on the community site and on my profile, but I still couldn't do it.

- Wiki module 1.4.2, 1.5.0
- Humhub 1.7.2, 1.8.0-beta.1
- Latest versions of Chrome and Firefox on Android10

**Comment by sakurafarm** [comment]
I'm sorry, I must have been mistaken.
I was able to change the order of the pages on my mobile device.

**Comment by sakurafarm** [comment]
In wiki v1.4.2 or later, loading `jquery.ui.touch-punch.js` is commented out in Assets.php.

The original `jquery.ui.touch-punch.js` hadn't been updated in a long time, so I made it load the [forked](https://github.com/RWAP/jquery-ui-touch-punch) `jquery.ui.touch-punch.js`, which solved the problem on mobile devices.

**Comment by buddh4** [comment]
Thanks for checking, maybe we should include this into the core.

**Comment by sakurafarm** [comment]
I'm happy to help.
