### ISSUE TITLE
Enable creating empty wiki page in Wiki link richtext modal

### ISSUE THREAD

**Issue by buddh4** [humhub/wiki#163]
Currently when adding a wiki link users can only select existing wikis. A user should be able to create a new wiki page (only by title and maybe category) in the same modal.

**Comment by luke-** [comment]
![image](https://user-images.githubusercontent.com/4736168/126778328-8082d3d5-132a-4c85-b132-1a08bb7f26a1.png)

**Comment by yurabakhtin** [comment]
@luke- I could implement this only with modification in core file - https://github.com/humhub/humhub/pull/5269.
PR of this module - https://github.com/humhub/wiki/pull/199

It works this way:
<img width="737" alt="new_wiki_page" src="https://user-images.githubusercontent.com/6995524/131808814-f9e12886-0c34-45ac-a9ee-cdfabf04a50c.png">

**Comment by luke-** [comment]
@yurabakhtin Works great, thanks!
