### ISSUE TITLE
Update from 1.5.0 to 1.5.2 makes pictures unusable

### ISSUE THREAD

**Issue by seraphyn** [humhub/wiki#169]
After updating from Wiki 1.5.0 to 1.5.2 all images in the spaces and in the wiki are only URLs and no longer available in the view. 

This was reproducible on two different installations
Here only a backup of the files and the database could be imported again

**Comment by luke-** [comment]
Can you please provide steps to reproduce?

I just tried the following steps without any problems:

1.) Install Wiki 1.5.0
2.) Create a Wiki page and insert an image
3.) Update to Wiki 1.5.2
4.) Open Wiki page and image is still displayed.

**Comment by luke-** [comment]
https://github.com/humhub/wiki/issues/171
