### ISSUE TITLE
Wiki page preview in stream not formatted

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/wiki#170]
**Problem description**

All the formatting (bold, italic, citation, ...) is not displayed in the preview of the wiki page in the stream since update to wiki 1.5.2 from 1.5.0

**Comment by luke-** [comment]
Maybe related to: https://github.com/humhub/wiki/issues/169

Unfortunately, I cannot reproduce the problem.

**Comment by luke-** [comment]
https://github.com/humhub/wiki/issues/171
