### ISSUE TITLE
Wiki Stream Entry without any Markup 

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#171]
Since this commit, there is no markup in the stream entries of the wiki module.
https://github.com/humhub/wiki/commit/5d84e176948f2089dbb3cc68119127efe7234971

We should revert this and use another output parser that at least supports the following:

- Text Markus
- OEmbed (Youtube)
- images

**Comment by yurabakhtin** [comment]
@luke- I have reverted the wiki page rendering code in PR https://github.com/humhub/wiki/pull/172:

<img width="663" alt="fixed_wiki_markup" src="https://user-images.githubusercontent.com/6995524/114715189-7a92bb80-9d3b-11eb-961b-b3ca5a309583.png">
