### ISSUE TITLE
File upload in "empty" wiki fails

### ISSUE THREAD

**Issue by aronbos** [humhub/wiki#173]
Php 7.4, Humub 1.82, Wiki 1.5.3
On my machine, if a user uploads a file, and it is the only entry in the wiki page, the upload will fail, with in the browser console the message:
`Form contains a file entry, but has no method = POST and enctype = multipart / form data in the form. The file will not be sent. `

That is very confusing for users uploading presentations in wiki's without any text.

Simply adding text to the wiki will prevent the upload failure, but that is hard to explain to stressed users.

**Comment by yurabakhtin** [comment]
@luke- I cannot reproduce this when I create a wiki page with single uploaded image into wiki page content by toolbar of richtext.

I can only guess from the console message that they submit some form which contains `<input type="file"...>` and the submitted `<form>` has no attribute `enctype="multipart/form-data"`.
But I cannot find where such form may exists with `<input type="file"...>` on wiki module.

@aronbos 

> and it is the only entry in the wiki page

Could you please tell us more details what you mean here? It would be better to see a screenshot, thanks.

**Comment by aronbos** [comment]
@yurabakhtin  In the latest version of Firefox and other browsers I can not replicate this error.
Users were simply uploading a pdf-file of a presentation in a wiki page with no further text on the page. So new page, upload file., that was it. It is working fine now, so this bug can be closed.
