### ISSUE TITLE
Option to add wiki pages to Space menu 

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#180]
It would be good to have an option for space administrators to shortcut important pages directly into the space navigation.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/182:

<img width="1149" alt="wiki_space_menu" src="https://user-images.githubusercontent.com/6995524/122575207-2cf73f80-d059-11eb-997c-46ef71b4d487.png">

Should I add acceptance test for this new option?

**Comment by luke-** [comment]
@yurabakhtin Yes. acceptance tests would be great.  A sort order field would also be great.  Please name the option "Show In Space menu"
We should also include the feature for User Profile Wikis.

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/wiki/pull/182/commits/283a61b1bc2858b640cd9719f5a4eaf3ae000778:

- Added new column `container_menu_order`,
- Implement the feature for Profile menu as well,
- Options have titles "Show in Space menu" and "Show in Profile menu"

Commit https://github.com/humhub/wiki/pull/182/commits/b9285548f0d6570ec023d0ae03fb45c4b0093f63:

- Acceptance tests for visibility of wiki pages in Space/Profile menu.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
