### ISSUE TITLE
Uploaded files fail to save without first clicking within content area

### ISSUE THREAD

**Issue by verement** [humhub/wiki#194]
When creating or editing a Wiki page:

- Without clicking in the “Page content” area, choose “Upload file” from the editor menu and select a file. The file is uploaded and a link appears within the page content editor.
- Still without clicking in the “Page content” area, click “Save” to save the page. The saved page is empty, and the uploaded file is missing.

The problem occurs if the “Page content” does not have focus when uploading the file or before clicking the “Save” button.

**Comment by luke-** [comment]
Sounds like:
https://github.com/humhub/humhub-prosemirror/blob/master/docs/CHANGELOG.md#115-may-5-2021

@verement Which HumHub version are you using?

**Comment by verement** [comment]
Hmm, could be.

This was on HumHub version 1.8.2.

**Comment by luke-** [comment]
@yurabakhtin Any idea?
