### ISSUE TITLE
Link colour for "Comment" & "Like"

### ISSUE THREAD

**Issue by orangiene** [humhub/wiki#201]
![comments](https://user-images.githubusercontent.com/62644500/132543278-769bf62b-37fc-4743-8fa7-0224e0762450.jpg)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/202:

<img width="1149" alt="link_colors" src="https://user-images.githubusercontent.com/6995524/132649240-40d808b4-5d71-4f4e-b267-a55f4ec6e806.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks!
