### ISSUE TITLE
1.6.0 Parallel Editing - Compare shows wrong text version

### ISSUE THREAD

**Issue by Semir1212** [humhub/wiki#204]
Instead of the current version, the original text version is shown when comparing.

Text: 

![image](https://user-images.githubusercontent.com/38326726/135417461-fbaddb48-60c9-4802-a08a-664075413319.png)

Compare:

![image](https://user-images.githubusercontent.com/38326726/135417547-85845006-196a-4f16-9e4a-168ea54e2c27.png)

**Comment by luke-** [comment]
@yurabakhtin It's related to the compare link in the parallel editing "overwrite" warning.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/wiki/pull/210:

<img width="724" alt="diff_current_editing" src="https://user-images.githubusercontent.com/6995524/135862573-f64f93aa-0c5c-439a-8258-7c4122e6928a.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks!
