### ISSUE TITLE
1.6.0 - Only one subcategory can be created

### ISSUE THREAD

**Issue by Semir1212** [humhub/wiki#205]
![image](https://user-images.githubusercontent.com/38326726/135418036-673c05c8-89cc-44af-b9de-0801dad271d4.png)

Once creating a single subcategory the error 'invalid category' appears, when trying to create another 'level' of subcategories. The error also appears when trying to add said new category to the main category instead. 

![image](https://user-images.githubusercontent.com/38326726/135418334-4db8d26f-8166-490c-a8ae-579c7f45794e.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/wiki/pull/208.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
