### ISSUE TITLE
1.6.0 - Going back overwrites own text version

### ISSUE THREAD

**Issue by Semir1212** [humhub/wiki#206]
When the message appears whether to overwrite another user's version and you go 'back', your own version is overwritten. 

Initial Text:

![image](https://user-images.githubusercontent.com/38326726/135419599-27ae9057-5523-4eee-8fde-cdc50219160f.png)

New Version User 1:
![image](https://user-images.githubusercontent.com/38326726/135420043-c5bad0b1-9247-458b-a87b-6a24a160c089.png)

New Version User 2:
![image](https://user-images.githubusercontent.com/38326726/135420117-5f7cc230-2353-4bf3-afc1-894fe825eb2d.png)

Warning; User 2 goes 'back':
![image](https://user-images.githubusercontent.com/38326726/135420195-fd0e82f8-18eb-40d6-974e-33beb583a80f.png)

Text of User 2 is overwritten by version of User 1:
![image](https://user-images.githubusercontent.com/38326726/135420235-853aad21-4e80-4d86-a3bc-8c59cf8456fa.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/wiki/pull/209.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
