### ISSUE TITLE
Print Version - Remove 'Powered by'

### ISSUE THREAD

**Issue by Semir1212** [humhub/wiki#207]
The line with 'Powerded by HumHub'+ Legal Tools pages are shown when printing a wiki. It is not need in this case.

![image](https://user-images.githubusercontent.com/38326726/135421406-a91093a3-c7de-49d0-bae8-8db07833c8c7.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/214.
