### ISSUE TITLE
1.6 shows category hierarchy where none exists

### ISSUE THREAD

**Issue by michaelh99** [humhub/wiki#215]
For example, when editing a wiki entry, the categories show something like:
```
Cat 1
Cat 2
- Cat 3
-- Cat 4
--- Cat 5
```

NONE of those categories have a parent category specified

**Comment by michaelh99** [comment]
I'm not sure what else to tell you.

I have categories set up similar to your last image.  In every case, the category has no parent yet they show as though they are parented.

![HumCat1](https://user-images.githubusercontent.com/2307675/136848261-3c9f5a21-d3f1-4200-9eb3-fb8530a13251.jpg)

**Comment by yurabakhtin** [comment]
@michaelh99 I think your issue is related to https://github.com/humhub/wiki/issues/205. Please check you use the latest version https://github.com/humhub/wiki/releases/tag/v1.6.0 especially with "Fix #205: Fix category selector".

**Comment by michaelh99** [comment]
@Oremountainflorian  exactly
