### ISSUE TITLE
Print Version - Space Name

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#216]
The Name of The Space that the wiki is in is printed at the top of the very first page, which is a nice touch!
But the space name & icon is also overlaid on each subsequent page, and it covers the text from the wiki.

![image](https://user-images.githubusercontent.com/4736168/136757696-bc7743e3-3503-4b9e-9a88-929fd335078c.png)

**Comment by luke-** [comment]
@yurabakhtin Thanks for the info. I'll check with the reporter again.

**Comment by Semir1212** [comment]
@yurabakhtin It seems to be connected to the Enterprise Theme Module. Could you please check again?

**Comment by yurabakhtin** [comment]
@Semir1212 Thank you for the details!
@luke- Fixed in PR https://github.com/humhub/wiki/pull/234.
