### ISSUE TITLE
Translations: missing space in 'Last updated '

### ISSUE THREAD

**Issue by DerGenaue** [humhub/wiki#219]
All/most translations are missing a space at the end of this translated text:

```
'Last updated ' => 'Letzte Aktualisierung',
```

This text is used in the header of a wiki page and followed by the Date in [`_view_header.php` L. 52](https://github.com/humhub/wiki/blob/master/views/page/_view_header.php#L52),
making translated versions read eg.:
`Letzte Aktualisierung11.11.2021 von Person`

## Proposed solutions:
Either
* Make sure to add the space in all translations
* remove the space from the original text and add it in the code
* Change the translation to a string with placeholder like in the humhub base `'Last updated {time}'`
* Just re-use the translated string mentioned above that already exists in the humhub base.

🍪 Here's a cookie to add to the dopamine kick from quickly fixing a small bug ;)

**Comment by luke-** [comment]
@DerGenaue The best solution would probably be #3, i.e. to introduce two new translations `Last update: {date}.` and `Last update at {date} by {user}.`

As a quick bugfix, however, the space in the source code would be ok from my side.

**Comment by DerGenaue** [comment]
Fair enough.
Is re-useing the translation from the main project even possible within this framework?

**Comment by luke-** [comment]
Yes, translations from the Core project can be used as usual. However, there is still no defined strategy and handling if e.g. core texts change.

**Comment by DerGenaue** [comment]
I think "no leading or trailing spaces in translated strings" should be a general rule because they will get missed out when doing translations and might even get auto-trimmed in the translation tools.
Thanks for merging the PR
