### ISSUE TITLE
Diff for page changes 

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#22]

**Comment by yurabakhtin** [comment]
@luke- As I understand we should implement a diff tool, and it should works on client side by JS, because the markdown source content is rendered by JS, right?
Probably we should find some js library like https://www.npmjs.com/package/html-differ, but I don't see how result looks.
Please tell me what result you expect:

- side-by-side
- line-by-line
- probably like this https://ourcodeworld.com/articles/read/653/how-to-diff-html-compare-and-highlight-differences-and-generate-output-in-html-with-javascript

Do you know some good js library for this purpose? Or should we create own diff tool?

**Comment by luke-** [comment]
Yes, exactly. Unfortunately, I don't know any libaries in that area. Do you like it just try what is available here?
I don't have any specific expectations here. 

I would try to use an existing library (if available) rather than developing something ourselves.

**Comment by yurabakhtin** [comment]
@luke- I have started only a view interface in PR https://github.com/humhub/wiki/pull/187, but I still need to choose a JS library for comparing differences in content.

<img width="959" alt="compare_view" src="https://user-images.githubusercontent.com/6995524/123415133-7e558080-d5bd-11eb-8688-f432b66ecbc8.png">

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/wiki/pull/187/commits/781e5602d21d8216049a315ff3ab4f8b1aca5f71: I could use only the JS file from this example https://ourcodeworld.com/articles/read/653/how-to-diff-html-compare-and-highlight-differences-and-generate-output-in-html-with-javascript.

<img width="957" alt="compared" src="https://user-images.githubusercontent.com/6995524/123634775-87e02200-d823-11eb-9022-5a51ce473a69.png">

This library has no options, it just adds the wrappers `<ins>` or `<del>` around changed text, but it doesn't do this around images. I think we should find better library but I cannot find enough good that works on client browser side.

**Comment by luke-** [comment]
@yurabakhtin I like your last example.
How does the library behave with other special elements like tables?

If you can't find any other proper diff library, we can do the side by side display and the ins/del markers (if supported).

**Comment by yurabakhtin** [comment]
@luke- 

> How does the library behave with other special elements like tables?

<img width="958" alt="diff_table1" src="https://user-images.githubusercontent.com/6995524/124128325-59618180-da85-11eb-9341-c030561f75c0.png">
<img width="957" alt="diff_table2" src="https://user-images.githubusercontent.com/6995524/124128342-5d8d9f00-da85-11eb-886c-74a067b2af50.png">

**Comment by yurabakhtin** [comment]
@luke- 

> If you can't find any other proper diff library, we can do the side by side display and the ins/del markers (if supported).

Yes, unfortunately I can't find other, but what do you mean "the side by side display and the ins/del markers", can you show an example how it should be visible?

**Comment by luke-** [comment]
@yurabakhtin  With "Side by Side", I mean your current solution.

I think that's so good as it is. We will use the library without image support for now. 
Maybe we can develop an image support for the JS Libarary sometime later?

**Comment by yurabakhtin** [comment]
@luke- 

> Maybe we can develop an image support for the JS Libarary sometime later?

Maybe yes, I think it would be better to find another library later, because currently you can see an image twice on the right side even if the image was not updated.

**Comment by luke-** [comment]
@yurabakhtin  Oh, I didn't realized the prob. Of course, we have to fix that before using the lib. 
Probably the duplicated image is because the "data-gallery-guid" changes dynamically?
Do you see a chance to adjust the libary here? Except for the problem, I actually find it quite nice.

**Comment by luke-** [comment]
@yurabakhtin Ah ok, I just see this is not a direct JS library but rather a cross compile. I'm afraid we'll have to look for something else. But I like the output of this lib.

**Comment by yurabakhtin** [comment]
@luke- I have implemented a quick solution to don't display the duplicate images in commit https://github.com/humhub/wiki/pull/187/commits/0fd80e9bce665d6bb3feab1004f0b7f3d410f31f, it looks like this now:

<img width="725" alt="fixed_dupl_img" src="https://user-images.githubusercontent.com/6995524/124290173-ce06ef80-db5b-11eb-8f3c-5fdc438b7491.png">

If you think it is ok we can merge the PR.

**Comment by luke-** [comment]
@yurabakhtin Ok, then the only problem is that images are not marked (when added/deleted/changed)?
That would be ok for now.  Is the PR ready to merge?

**Comment by yurabakhtin** [comment]
@luke- 

> then the only problem is that images are not marked (when added/deleted/changed)?

Yes, only this problem.

> That would be ok for now. Is the PR ready to merge?

Yes, I have changed the status to "Ready for review".

**Comment by luke-** [comment]
@yurabakhtin ok Thanks!
