### ISSUE TITLE
Wiki CSS loads after the Theme and custom CSS

### ISSUE THREAD

**Issue by lisandi** [humhub/wiki#221]
Wiki CSS loads after the Theme and custom CSS and therefore can't get overwritten easily by custom themes
![Screen Shot 2021-11-13 at 23 34 44](https://user-images.githubusercontent.com/1982011/141676950-b2af22c3-233d-4da1-89be-75ad305766a2.png)

Changes in Custom CSS files won't affect the Wiki Pages!

Solution would be to load the WIKI and any other Module CSS before the custom CSS

**Comment by schlagmichdoch** [comment]
Have you tried ` padding: 2px 15px !important` ?

**Comment by lisandi** [comment]
It is actually not good practice to use important to substitute or correct the loading mistakes of a module's CSS. ;-)  I would suggest correcting the problem at its source and this means that the custom CSS parts have to be loaded at the end after all other CSS, including Module CSS parts had been loaded. It is otherwise very hard to create proper custom themes and maintain those if you have to look in tons of other CSS scripts instead of if you constantly have to replicate an already existing complete CSS only because you are changing one CSS value i.e. like the one above.
