### ISSUE TITLE
Adding an internal wiki link doesn't close the overlay properly

### ISSUE THREAD

**Issue by aaukt** [humhub/wiki#226]
When adding an internal wiki link the overlay for adding isn't closed properly when saved. The div with id="wikiLinkModal" keeps the style "display:block" and thus makes it impossible to save the change. Setting it manually to display:none with dev-tools makes it usable again.

Additionally the LinkModal doesn't show when editing in fullscreen-mode.

Humhub Version: 1.10.1
Wiki Version: 1.6.2

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/wiki/pull/227.

**Comment by man10to** [comment]
Hello,
where or how can I 
"Setting it manually to display:none with dev-tools makes it usable again." ???

best regards Egbert

**Comment by aaukt** [comment]
Apparently this is already fixed in master, @luke- will there be a patch release?

**Comment by luke-** [comment]
@aaukt I've just released Wiki 1.7

**Comment by man10to** [comment]
Hello, Thanks,

it is working

best regards 

Egbert

 

Von: Lucas Bartholemy ***@***.***> 
Gesendet: Donnerstag, 27. Januar 2022 15:18
An: humhub/wiki ***@***.***>
Cc: man10to ***@***.***>; Comment ***@***.***>
Betreff: Re: [humhub/wiki] Adding an internal wiki link doesn't close the overlay properly (Issue #226)

 

@aaukt <https://github.com/aaukt>  I've just released Wiki 1.7
