### ISSUE TITLE
Add or remove wiki link freezes the editor

### ISSUE THREAD

**Issue by man10to** [humhub/wiki#231]
Hello,
since a week or so the editor freezes after add a wiki link. it isn't posible to save the change. When reloading the page the changes are gone.
I have testest this behavior on 3 different instances and 4 computers, ipads and firefox and Chrome.
is this issue kown ?

best regards from germany 
Egbert

**Comment by vsemradu** [comment]
specify which editor? this?
![screenshot_4](https://user-images.githubusercontent.com/10543601/151152629-a1f6d807-5cfb-43aa-9924-8a703a205c21.png)

**Comment by luke-** [comment]
@vsemradu I think the Wiki Page Editor is meant. Here you can also link wiki pages to each other.

**Comment by yurabakhtin** [comment]
probably it was fixed here https://github.com/humhub/wiki/issues/226

**Comment by man10to** [comment]
hello, thanks for your hint,
where or how can in change this
best regards Egbert

**Comment by luke-** [comment]
@yurabakhtin Thanks for the ino.
I've just released the Wiki Module 1.7.0

Please reopen the issue if the bug presists....
