### ISSUE TITLE
Wrong order of Comment and Like link

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/wiki#232]
Normally, HumHub shows the Comment/Reply link before the Like link.
But in Wiki pages it is the other way round.

That is a bit confusing.
I don't know which order is better but it should be the same everywhere.

Thanks for the great module and your work.

![Screenshot](https://user-images.githubusercontent.com/84990763/151717256-a039d712-1c23-4f25-a3b5-ef7439bcd5cd.png)

**Comment by luke-** [comment]
@s-tyshchenko Why not just change it to `ContentObjectLinksBase`?

**Comment by luke-** [comment]
@s-tyshchenko Sorry for the confusion, I've fixed it here:
https://github.com/humhub/humhub/commit/7c11e4579ec82a7458facd9a49fb3bace05f8461
