### ISSUE TITLE
Markdown Quotes tag does not work

### ISSUE THREAD

**Issue by Vatarus** [humhub/wiki#24]
See screenshots
![wiki01](https://cloud.githubusercontent.com/assets/3394915/6933182/d1000cbe-d85e-11e4-8218-64b04149a866.png)
![wiki02](https://cloud.githubusercontent.com/assets/3394915/6933183/d101407a-d85e-11e4-9d74-093b74755d05.png)

**Comment by WASasquatch** [comment]
Using the Editor to Insert a List will not work. It will only do the first list element `1.` and after a line break, exists list mode. Clicking the list button again inserts another list at entry point `1.`

**Comment by funkycram** [comment]
+1 for the Quote bug !

**Comment by sebasunlam** [comment]
Any update on this?

**Comment by acs-ferreira** [comment]
Confirmed here too.
