### ISSUE TITLE
Wiki - Add Configuration for option to NOT post wiki page additions or changes to Stream

### ISSUE THREAD

**Issue by buddycollins** [humhub/wiki#248]
The Wiki is very useful and comes with it's own navigation. I would like to reserve the Stream for user posts and not have it cluttered up with all of the edits and changes to the Wiki. Users can browse Wiki  through Wiki navigation. 

Marc Farré suggest editing the following page:
/var/www/humhub/protected/modules/wiki/models/WikiPage.php
.. and changing ... $autoAddToWall = true
to $autoAddToWall = false

I tried that, but it didn't alter the behavior of the Wiki. Adding new pages to the Wiki still resulted in new posts to the Streams. 

Here's my code change below, which didn't work.

![image](https://user-images.githubusercontent.com/77176757/193469211-2e80c734-cfe2-44ca-877e-9fcc327fe21c.png)

**Comment by luke-** [comment]
At the moment this is not possible.

You can use this option:
https://community.humhub.com/s/installation-and-setup/wiki/Configuration+Examples#stream-hide-content-types
