### ISSUE TITLE
Allow Wiki pages with the same name

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#256]
With the new navigation & cateogization capabilities, it would be useful to also allow pages with the same titles.

**Comment by Toastbrotbaby** [comment]
+1

**Comment by Toastbrotbaby** [comment]
After closing #270 (thank you!) it would be really useful to name active sites with the same title. Perhaps internally with a category key?

**Comment by marc-farre** [comment]
@luke- Would you accept a PR changing [`WikiPageUrlRule` class](https://github.com/humhub/wiki/blob/master/components/WikiPageUrlRule.php) with this behavior (e.g, the wiki page ID is `2422`):
- Adding the `ID` into the URL (as [you suggested it here](https://github.com/humhub/humhub/issues/6898#issuecomment-2016795207)): `/s/some-space/wiki/2422/Some+Test+Page+Title`
- If the `2422` ID is not present (for old URLs), the URL still works: `/s/some-space/wiki/Some+Test+Page+Title`
- If the `2422` ID is present, but the title has changed, the URL still works because when the ID is present in the URL, we don't look at the title (it's only for SEO and human-readable purpose).

**Comment by felixhahnweilheim** [comment]
Wouldn't it be better to add a new field "URL slug" that has to be unique?
By default it is Some+Page+Title (or Some+Page+Title2 for a duplicate title) but it can be edited.
(The only questions if editing the URL should be limited to space admins and the author.)

That would be prettier than an ID in the URL, also for SEO or sharing the link.

And the permalink could be left how it is.

**Comment by Toastbrotbaby** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






Wouldn't it be better to add a new field "URL slug" that has to be unique?
By default it is Some+Page+Title (or Some+Page+Title2 for a duplicate title) but it can be edited.
(The only questions if editing the URL should be limited to space admins and the author.)

That would be prettier than an ID in the URL, also for SEO or sharing the link.

And the permalink could be left how it is.

**Comment by luke-** [comment]
Hmm not sure, a URL slug makes sense in areas like (Spaces or CustomPages), but for the Wiki, that would probably be too much.  (Additional field which has to be maintained). 

I would rather prefer the solution suggested by Marc.

**Comment by Toastbrotbaby** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






Hmm not sure, a URL slug makes sense in areas like (Spaces or CustomPages), but for the Wiki, that would probably be too much.  (Additional field which has to be maintained). 

I would rather prefer the solution suggested by Marc.

**Comment by Toastbrotbaby** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






@luke- Can I remove [`humhub\modules\wiki\Markdown` class](https://github.com/humhub/wiki/blob/master/Markdown.php)?
I cannot find any usage of it. And it's unusual to have such a class directly in the root of the module.
Or maybe there's something I didn't understand?

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/wiki/pull/324/

I've removed [`humhub\modules\wiki\Markdown` class](https://github.com/humhub/wiki/blob/master/Markdown.php) as mentioned on my above comment.

**Comment by Toastbrotbaby** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






@luke- PR https://github.com/humhub/wiki/pull/324/

I've removed [`humhub\modules\wiki\Markdown` class](https://github.com/humhub/wiki/blob/master/Markdown.php) as mentioned on my above comment.

**Comment by luke-** [comment]
@marc-farre Thanks! I think the removed class is ok.

**Comment by Toastbrotbaby** [comment]
Sehr geehrte Damen und Herren,

bis inklusive 03.04.2024 bin ich nicht im B++ro und lese meine Mails nur unregelm+ñ+ig.

Bitte wenden Sie sich in dringenden F+ñllen an das B++ro unter ***@***.***

Ihre Mail wird nicht automatisch weitergeleitet.




Mit freundlichen Gr+++en

Thorsten Altmann






@marc-farre Thanks! I think the removed class is ok.
