### ISSUE TITLE
Category cannot be deleted

### ISSUE THREAD

**Issue by DaKeks** [humhub/wiki#257]
Categories cannot be deleted / edited.

1. Create new page
2. Enter a title, e.g. "TEST"
3. Check "is category" under advanced settings
4. Save
5. Edit page
6. Delete and confirm
7. You will be forwarded to index where category still exists
8. Category cannot be deleted

Further notes: It behaves quite "strange" because after clicking the category, the form for creating a new page is displayed including the category name as title...

**Comment by luke-** [comment]
Should be fixed with the latest update.
