### ISSUE TITLE
New page is created but not displayed

### ISSUE THREAD

**Issue by DaKeks** [humhub/wiki#258]
New pages are not displayed after creation.

1. Create new page
2. Enter a title, e.g. "TEST"
3. Save
4. Page is not displayed
5. New page with same title cannot be created

**Comment by DaKeks** [comment]
I created a video using your hosted humhub service: https://youtu.be/Vk2yoqdANhg
Same issue on self hosted instance.

**Comment by luke-** [comment]
@gevorgmansuryan Can you please take a quick look?

FYI: We'll soon release a bigger update of the Wiki module here: https://github.com/humhub/wiki/pull/249

**Comment by noratchi** [comment]
@DaKeks @luke- @gevorgmansuryan 

I have the same problem, albeit slightly different.

- Cannot create a wiki page with the same title as a deleted wiki page.
- This occurs for both user profile and space. 
- If the wiki module is uninstalled in this state, a server error will occur when accessing the space where the wiki page was deleted or the profile page.
-  `HumHub 1.14.0` `wiki 1.8.0, 1.9.0-beta.1`

**Steps to reproduce a problem**

1. Create a new wiki page from a space or user profile
2. Enter a title (e.g., "TEST") and save
3. Delete page
4. Repeat steps 1 and 2 (with same title)
5. Page cannot be saved.
![2023-04-30_10h28_10](https://user-images.githubusercontent.com/88924901/235333017-9fb31747-622f-406f-8dee-ccf8991a86b1.png)

After this, if the wiki module is uninstalled, the space where the wiki page was created
or attempting to open a user profile will result in a server error.

Deleted wiki page records remain undeleted in the content table of the database.

I tried to delete the record by running `php yii integrity/run` from the terminal, but it does not delete the record.

I was able to recover from the server error by manually deleting the record.

**Comment by luke-** [comment]
Sounds to be related to the new Soft Delete System.

**Comment by yurabakhtin** [comment]
@luke- I cannot reproduce the issue of the hidden page right after creating too.

PR https://github.com/humhub/wiki/pull/259:
- hard delete all wiki pages on disable module.
- Display new error message if a page with same title was soft deleted:

![error_same_soft_deleted_page](https://user-images.githubusercontent.com/6995524/235430670-767a772b-b4e2-41ec-aa52-696a04f837c2.png)

I think we should to improve this case, for example, we could display additional button like "Overwrite"(with style red/danger), so the soft deleted page with same title will be replaced with data from the submitted form and make the page published.
Also we can add a message like "If you want to restore and update the deleted page please press the button "Overwrite"".
Do you agree this solution?
