### ISSUE TITLE
Deleted content still showing up

### ISSUE THREAD

**Issue by WizWareTech** [humhub/wiki#268]
**For wiki content that existed prior to 1.14.x upgrade, when deleting:**

1. The page still shows up in the wiki despite being deleted.
2. When you click on it, it brings up a page to create a new wiki with the same name.
3. If you try to create a new page with the same name, you get error 'Page title already in use for a deleted page!'

Ideas to fix:

- When existing content is deleted, that it no longer shows up.
- For existing items that are now stuck in this limbo state, will the code alleviate that or does a query need to be run to fix this inconsistency in the database?

**For wiki content created after 1.14.x upgrade, when deleting:**

1. The content does not show up in the wiki (as expected).
2. When you try to create a new wiki with same name, you still get error 'Page title already in use for a deleted page!'

Ideas to fix: The code should be fixed to allow a page to be created despite there being a deleted page with the same name. One solution I can think of is to use unique IDs for primary keys instead of names. Another solution would be to add ' DELETED ON XXXX-XX-XX) to the name of a deleted wiki, so there is no naming conflict if someone should want to create a new wiki with the same original name.

**Comment by yurabakhtin** [comment]
@WizWareTech 

> **For wiki content that existed prior to 1.14.x upgrade, when deleting:**
> 
> 1. The page still shows up in the wiki despite being deleted.

Could you please tell what version of the module "Wiki" you use?
I don't see the deleted files in wiki pages list and on space stream, could you show a screenshot or url(like `/s/space-name/wiki/overview/list-categories` or stream `/s/space-name/home`) where you find the deleted wiki pages?

> **For wiki content created after 1.14.x upgrade, when deleting:**
> 
> 1. The content does not show up in the wiki (as expected).
> 2. When you try to create a new wiki with same name, you still get error 'Page title already in use for a deleted page!'

We fixed this here https://github.com/humhub/wiki/pull/276 some days ago.

Thanks.

**Comment by WizWareTech** [comment]
Now when I delete a wiki, it disappears from the list (as I would expect, even though it is only soft-deleted). You must have fixed it, thank you!

I do still think it would make the most sense that when an item is soft-deleted, that somehow the name is modified (perhaps adding 'DELETED-xxxxxxxx' where xxxxxxxx is random number. That way, if an item is soft-deleted, you can still make a new item with the same name without having to wait 24 hours in order to do so. Then if an item is undeleted, you could change it to 'UNDELETED-xxxxxxxxx'. That way there would be no duplicates, and after someone undeletes, they can always rename it right there. Just a thought... the issue is that a soft-deleted item is unknown to the user and they may not realize why they can't create a new item with that name if they can't see it there.

**Comment by yurabakhtin** [comment]
> I do still think it would make the most sense that when an item is soft-deleted, that somehow the name is modified (perhaps adding 'DELETED-xxxxxxxx' where xxxxxxxx is random number. That way, if an item is soft-deleted, you can still make a new item with the same name without having to wait 24 hours in order to do so. Then if an item is undeleted, you could change it to 'UNDELETED-xxxxxxxxx'. That way there would be no duplicates, and after someone undeletes, they can always rename it right there. Just a thought... the issue is that a soft-deleted item is unknown to the user and they may not realize why they can't create a new item with that name if they can't see it there.

@WizWareTech We implemented to rename a wiki page title to `conflict123-page title` (`123` is ID of the soft deleted page, `page title` - is title of the soft deleted page) here https://github.com/humhub/wiki/pull/276. This renaming is executed only when another page is creating with same title. It was discussed here https://github.com/humhub/wiki/issues/270.
I.e. after the fix you can create a wiki page with same title without having to wait 24 hours because the old soft deleted will be renamed automatcally at that time when you create another page with same title.
I don't see a reason to do the renaming right at that time when page is deleted.

**Comment by WizWareTech** [comment]
I think that should work. When will this be done so I can test? (the only updating I know how to do is via the update module, I haven't updated directly via cli because I don't know how to do properly and don't want to break anything)
