### ISSUE TITLE
A editable wiki page should have be editable from the stream

### ISSUE THREAD

**Issue by funkycram** [humhub/wiki#269]
Steps to reproduce:
1. Go to the wikipage (e.g. https://community.humhub.com/s/hosting/wiki/Homepage)
2. If you are a member of the space, you'll see the "Edit" button"
3. Go to the stream page (e.g. https://community.humhub.com/s/hosting/home)
4. You don't see the "Edit" menu entry:
![image](https://github.com/humhub/wiki/assets/23310825/6dc176cd-5ea1-4bd5-9da4-c7a9b942b558)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/wiki/pull/271.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
