### ISSUE TITLE
Deleted titles cannot be used a second time

### ISSUE THREAD

**Issue by Toastbrotbaby** [humhub/wiki#270]
After deleting a page, no page can be created with the same title.
If a distinction is made between soft and hard deletion: Where is this manageable?

**Comment by luke-** [comment]
@yurabakhtin I would prefer a solution like the CFiles module to rename the deleted Page in conflict situations. Or this already fixed with v2 in other way?

**Comment by yurabakhtin** [comment]
@luke- I find this separate PR https://github.com/humhub/wiki/pull/259 where we made to display an error `Page title already in use for a deleted page!` for the case, it looks like screenshot from this comment https://github.com/humhub/wiki/issues/258#issuecomment-1529493101, also I suggessted solutions:

> I think we should to improve this case, for example, we could display additional button like "Overwrite"(with style red/danger), so the soft deleted page with same title will be replaced with data from the submitted form and make the page published.
Also we can add a message like "If you want to restore and update the deleted page please press the button "Overwrite"".
Do you agree this solution?

As I understand you didn't agree that so to be sure please confirm we should silent rename old deleted page with same title as we do for CFiles module.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the overview. 

I prefer the solution of simply renaming a SoftDeleted content. After we already using this approach in CFiles, I would do it the same way here.

**Comment by yurabakhtin** [comment]
> I prefer the solution of simply renaming a SoftDeleted content. After we already using this approach in CFiles, I would do it the same way here.

@luke- Ok, done in PR https://github.com/humhub/wiki/pull/276.
