### ISSUE TITLE
Page Index - Level Padding

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#274]
We recently reduced the paddings in the EE theme. 
In the CE theme, however, a larger padding is necessary here.

Enterprise Theme:
![image](https://github.com/humhub/wiki/assets/4736168/efef9f88-fa85-4d59-8c3e-c6026796b84e)

Community Theme:
![image](https://github.com/humhub/wiki/assets/4736168/1201b82f-b65b-4393-bfb6-2c39a908e14e)

@Eladnarlea Can you take a look?

**Comment by WizWareTech** [comment]
I can confirm this is a problem.
![image](https://github.com/humhub/wiki/assets/13114/00e95c2a-18a0-4c84-b541-419ac900a112)
This is in clean-base theme as well.

The incorrect padding makes it very confusing to the end user. This is what it should look like:
![image](https://github.com/humhub/wiki/assets/13114/076feeec-4457-4f50-a36e-6d0b3ba357ff)

(it needs several adjustments to line things up properly, even when there is a 'down-arrow' for sub-items.

I was able to locate CategoryListView.php and change:
   public $levelIndent = 47;

And I got this:
![image](https://github.com/humhub/wiki/assets/13114/f9cb6eaf-7446-41fe-9ed1-bfa83d6aa7e9)

that is better, but still missing the proper indent on the categories that don't have the drop-down icon. It should look like this:
![image](https://github.com/humhub/wiki/assets/13114/cec7d9a6-caae-44a5-b94a-0bb73e925f4f)

I wish I knew more and could find what to change easily, but I'm sure the developers can fix this quickly and easily (and if someone could tell me where to find it in the meantime, I would be most appreciative!)

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea Fixed in PR https://github.com/humhub/wiki/pull/280:

![level-indent-default-theme](https://github.com/humhub/wiki/assets/6995524/832a6446-ca23-4af0-8989-9df63ab454f3)

**Comment by luke-** [comment]
@Eladnarlea Should be available on your test installation leandraa. Can you please check?

**Comment by Eladnarlea** [comment]
I think we should indent it a tad more. What do you reckon? @yurabakhtin 

<img width="1055" alt="Screenshot 2023-08-08 at 8 14 30 AM" src="https://github.com/humhub/wiki/assets/105652258/f18775f8-9750-4c79-9d7f-c40bce94d80c">

**Comment by yurabakhtin** [comment]
> I think we should indent it a tad more. What do you reckon? @yurabakhtin

@Eladnarlea For me current space size looks sufficient. If you prefer to have a different spaces on sidebar and here please let me know, but please note it will require to keep two different style codes, also as you can see on my screenshot the titles may be long with 3 dots, so it would be better to keep more space on the left side.

**Comment by Eladnarlea** [comment]
@yurabakhtin okay, let's keep it this way for now. :)

**Comment by WizWareTech** [comment]
Thank you all for jumping on this. I am excited to test new code when it is released to the marketplace. I am happy to test it beforehand if someone can tell me how to manually install the latest code and I am happy to provide feedback too.
