### ISSUE TITLE
Theme - font size of categories in the index page too big? (version Version 2.0.0-beta.1)

### ISSUE THREAD

**Issue by funkycram** [humhub/wiki#278]
@Eladnarlea what do you think about the font size of categories in the index page?

E.g.
https://community.humhub.com/s/module-development/wiki/overview/list-categories

![image](https://github.com/humhub/wiki/assets/23310825/fbfd5bc4-bf96-45fe-82dc-946f524576ce)

I suggest 14 px instead of 16px:

![image](https://github.com/humhub/wiki/assets/23310825/c1b01163-6fdc-41c8-802e-1a09e460c4d8)

**Comment by Eladnarlea** [comment]
@funkycram @luke- I have been playing around a bit and I agree, it makes sense to reduce the font size for the index panel titles to 14px.

**Comment by Eladnarlea** [comment]
I think we should also adapt the `14px and font-weight: 500` to the "Last Edited" headlines, too. 

<img width="1058" alt="Screenshot 2023-08-07 at 9 02 07 AM" src="https://github.com/humhub/wiki/assets/105652258/e59209af-5dc3-49fe-9893-84ad17190108">

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look. Let us know when you  need further info

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- PR https://github.com/humhub/wiki/pull/282:

![wiki-index](https://github.com/humhub/wiki/assets/6995524/18a1ceab-6bcb-427d-a0be-6794bcb9a4b6)

![wiki-last-edited](https://github.com/humhub/wiki/assets/6995524/eba4ce72-8b9c-4a94-90b8-c92070651d46)

![wiki-sidebar](https://github.com/humhub/wiki/assets/6995524/d2677c2e-6268-4594-9739-8733bb2f6262)

**Comment by luke-** [comment]
@Eladnarlea I've updated your test site. Can you please check?

**Comment by Eladnarlea** [comment]
I checked EP and CE and it looks good on both. Thank you very much, @yurabakhtin!

**Comment by funkycram** [comment]
Thanks!
