### ISSUE TITLE
Wiki Stream Entry - Teaser Text

### ISSUE THREAD

**Issue by funkycram** [humhub/wiki#279]
E.g. https://community.humhub.com/s/module-development/home?filters_visible=1&includes[]=humhub\modules\wiki\models\WikiPage

![image](https://github.com/humhub/wiki/assets/23310825/d254c413-b362-4620-889c-b02ecc6d38be)

**Comment by luke-** [comment]
Currently we use the text before the first headline as Text teaser. Inside the Wiki Page we display it before the ToC.

e.g.

![image](https://github.com/humhub/wiki/assets/4736168/6ef75ab6-c2d4-4781-bca1-60ccc527111a)

I would suggest, to display this text in the Stream Entry as well.

If no text is before the first headline, I could not show any content in the Stream Entry.

@Eladnarlea @funkycram What do you think about this approach?

**Comment by funkycram** [comment]
I think most users won't be aware of this behavior. It seems to me that it would be better to show the beginning of the page, regardless of the type of content.

**Comment by luke-** [comment]
> I think most users won't be aware of this behavior. It seems to me that it would be better to show the beginning of the page, regardless of the type of content.

Hmm, maybe we could do this as fallback. But should we really render the full markup here? e.g. different text sizes, tables, images, ...

**Comment by funkycram** [comment]
I let @Eladnarlea answer because she will have a better approach than me! But I think a fallback is a good idea.

**Comment by Eladnarlea** [comment]
@funkycram we are currently working on a redesign to unify and enhance wall-entry postings on the dashboard. As part of this there will also be a Wiki-Wall-Entry Redesign in order to make the content of the wiki entry more clear for the user. (future design development will also take wiki entry creation & structuring into account)

Hence I would suggest that we go with your suggestions for now, with the aim of improving them soon:

1. if there is a teaser text, we display the teaser text first, and head of the page second
2. if there is no teaser text then we display the head of the page as wall entry on dashboard as it is. 

What do you guys reckon? @funkycram @luke-

**Comment by funkycram** [comment]
Thanks for the info. OK for me.

**Comment by luke-** [comment]
Fine for me too. 

@yurabakhtin Can you please take a look into this?

**Comment by yurabakhtin** [comment]
@Eladnarlea Could you please give more details to know what exactly and where we should display?

> Hence I would suggest that we go with your suggestions for now, with the aim of improving them soon:
> 
> 1. if there is a teaser text, we display the teaser text first, and head of the page second
> 2. if there is no teaser text then we display the head of the page as wall entry on dashboard as it is.

![wiki-wall-entry](https://github.com/humhub/wiki/assets/6995524/ace4a830-c2f2-4045-9477-df2bac30f074)

- The teaser is a text before first header in the wiki page content, right?
- Should we remove the text after teaser from wall entry completely?
- Should we render the text on wall entry as we see on the wiki page view?

**Comment by Eladnarlea** [comment]
@yurabakhtin I will take a look into it tomorrow morning! :)

**Comment by Eladnarlea** [comment]
> * The teaser is a text before first header in the wiki page content, right?

**Yes**

__________
> * Should we remove the text after teaser from wall entry completely?

**No**

__________
> * Should we render the text on wall entry as we see on the wiki page view?

yes I actually thought it would look like that already. Let's format the text like we see it on the wiki page.

**Comment by yurabakhtin** [comment]
@luke- @Eladnarlea Done in PR https://github.com/humhub/wiki/pull/283:

Wall entry:
![wiki-wall-entry](https://github.com/humhub/wiki/assets/6995524/7234e0e6-ed05-424e-9e3c-05ccc18f751c)

Wiki page:
![wiki-view](https://github.com/humhub/wiki/assets/6995524/a6031bc4-aecf-4888-bb51-4ba3eac85495)

**Comment by Eladnarlea** [comment]
I think it looks good. I really like it! :)

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
