### ISSUE TITLE
force house icon to big size when no more crumb path items

### ISSUE THREAD

**Issue by Eladnarlea** [humhub/wiki#287]
<img width="960" alt="Screenshot 2023-08-14 at 9 25 32 AM" src="https://github.com/humhub/wiki/assets/105652258/ca33058b-b3d8-430e-962c-4c10aa9569fb">

**Comment by yurabakhtin** [comment]
@Eladnarlea @luke- Done in PR https://github.com/humhub/wiki/pull/288:

![home-icon-forced](https://github.com/humhub/wiki/assets/6995524/84564668-2824-4706-b3dd-1ed7d9071bb6)
