### ISSUE TITLE
can create a table ?

### ISSUE THREAD

**Issue by ghost** [humhub/wiki#29]
Hello how create a table please ?

**Comment by xaro1** [comment]
+1 !!!

**Comment by fgreiner** [comment]
+1!

**Comment by theexit** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by elpoto** [comment]
Table Helper/Plugin would be great!

**Comment by juliancesar** [comment]
+1

**Comment by 001101** [comment]
On Zenndesk is a good guide, i have copied the HTML and extended it for the users on my hub
https://support.zendesk.com/hc/de/articles/203691016-Formatieren-von-Text-mit-Markdown
