### ISSUE TITLE
Error reactivating old/last revision of an wiki article

### ISSUE THREAD

**Issue by optitsolutions** [humhub/wiki#294]
{
    "url": "/index.php?r=wiki%2Fpage%2Frevert&id=242&cguid=c9f7b36f-266f-4fb9-8bf4-64bd843557f5",
    "status": 400,
    "response": {
        "error": true,
        "message": "Pflichtparameter fehlen: toRevision"
    },
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"error\":true,\"message\":\"Pflichtparameter fehlen: toRevision\"}",
        "responseJSON": {
            "error": true,
            "message": "Pflichtparameter fehlen: toRevision"
        },
        "status": 400,
        "statusText": "error"
    },
    "dataType": "json",
    "error": true,
    "message": "Pflichtparameter fehlen: toRevision",
    "errorThrown": "",
    "validationError": true
}

**Comment by optitsolutions** [comment]
parameter "toRevision" is missing.

**Comment by optitsolutions** [comment]
@luke- if you need more information from me, please specify...
Each time I try to change to an old version of a wiki site I get this error.

**Comment by yurabakhtin** [comment]
@optitsolutions Thank you for the reporting!
@luke- Fixed in PR https://github.com/humhub/wiki/pull/295 the bug:

![missed-revision](https://github.com/humhub/wiki/assets/6995524/f4f97ff7-dab1-49b2-8c48-5110d96edd1e)
