### ISSUE TITLE
Use the custom module name in the overview page, page title and sidebar

### ISSUE THREAD

**Issue by marc-farre** [humhub/wiki#299]
If the module name is changed in a space:
![image](https://github.com/humhub/wiki/assets/23310825/7e313a6b-3de7-4fe6-b199-fc7462873140)

The custom name should also be used in the overview page:
![image](https://github.com/humhub/wiki/assets/23310825/ab235b64-2944-4daa-8103-6400f24706b8)

And also on the page title displayed on the browser's tab and the sidebar for the Enterprise theme.

**Comment by marc-farre** [comment]
@luke- https://github.com/humhub/wiki/pull/300 if you agree about these changes.

**Comment by marc-farre** [comment]
@luke- What do you think about this PR? Thanks!

**Comment by luke-** [comment]
@marc-farre Thank you I've merged it. (Even if I'm not a big fan of customizable module names).

**Comment by marc-farre** [comment]
> I'm not a big fan of customizable module names

Yes, I agree, it's not very logic to be able to do this.
But for the wiki module, it's really a great feature, because we can use it as "Super custom pages"!
It's nice for writing a documentation, or things like that.
