### ISSUE TITLE
[HumHub Community] Text field disappears when changing editor mode

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/wiki#304]
### What steps will reproduce the problem?
- Create a new Wiki page on community.humhub.com
- Switch the editor to Markdown
- Type some markdown (e.g. `# Test`)
- Switch back to normal editor mode

### What is the expected result?
The editor translates the Markdown into normally formatted text (or tries to translate as much as possible).

### What do you get instead?
The whole content field disappears.

![Screenshot 2024-01-09 at 22-24-47 Übersicht - HumHub Community](https://github.com/humhub/humhub/assets/84990763/d2d315ee-8f33-41e2-b3dd-d9032fc53451)

### Additional info
This console error appeared 2 times:
> Uncaught Error: Token type `html_inline` not supported by Markdown parser [humhub-bundle.js:1:683533](https://community.humhub.com/static/js/humhub-bundle.js?v=1704571971)

| Q                | A
| ---------------- | ---
| HumHub version   | community.humhub.com

**Comment by felixhahnweilheim** [comment]
Strangely the bug does not appear in my own instances, only on community.humhub.com but there it is reproducable.

**Comment by yurabakhtin** [comment]
@felixhahnweilheim I cannot reproduce this on my profile here https://community.humhub.com/u/yurabakhtin/wiki/page/edit on Chrome browser Windows 11.

![test-wiki-editor](https://github.com/humhub/wiki/assets/6995524/14e8e0d8-e0ce-4d21-a5ca-b701259564a7)

![test-wiki-editor2](https://github.com/humhub/wiki/assets/6995524/858a0f4b-acc0-4dd8-893b-78b9529c5a41)

Maybe you should try to refresh browser cache, probably some old wrong versions of the Markdown editor is cached.

**Comment by felixhahnweilheim** [comment]
Thanks for trying. Now I also can't reproduce it any more. So it was probably a cache issue.
