### ISSUE TITLE
Add H3 titles to the Table Of Contents (TOC)

### ISSUE THREAD

**Issue by marc-farre** [humhub/wiki#319]
Currently, the TOC is generated from H1 and H2 titles.
Sometimes, we need to include H3 titles too, which could create a third level of titles.

**Comment by marc-farre** [comment]
@luke- if you agree, I can send a PR to add H3 titles to this code: https://github.com/humhub/wiki/blob/master/resources/js/humhub.wiki.Page.js#L82-L139

**Comment by luke-** [comment]
Hmm, not sure. we shouldn't overfill the TOC either.

Can we perhaps find an intelligent logic? e.g. if there are under 20x `h3`, include them, otherwise only `h1` & `h2`?

Other suggestions also welcome.

**Comment by marc-farre** [comment]
@luke- Yes, good idea.
Maybe I could add this `20x` value as a public attribute of the `Module` class, allowing to be changed in `config/common.php` ?

**Comment by luke-** [comment]
@marc-farre Yes, a public attribute would be fine.

@Eladnarlea What do think about this?

**Comment by Eladnarlea** [comment]
@luke- I believe that most of the `h3` titles are longer and more explanatory in some cases. Therefore we would probably need to adjust the width of the TOC Box to display the titles, also due to the indent of the headlines.

**Comment by Eladnarlea** [comment]
@luke- actually, we don't need to adjust anything. I have just checked it and the TOC Box naturally has a width of 50% of the wiki panel. On mobile it is full width of course. I think it will look okay, at least from what I can tell viewing dev mode in my browser.

@marc-farre could you indent the `h3- text` using around 28px to 30px, please? It should be less indented than the `h1` to `h2` jump

![Screenshot 2024-03-25 at 12 20 17 PM](https://github.com/humhub/wiki/assets/105652258/0fd8c1f6-0d95-4da0-858b-5e7bd65c3b12)

**Comment by marc-farre** [comment]
@luke- @Eladnarlea PR https://github.com/humhub/wiki/pull/323

![image](https://github.com/humhub/wiki/assets/23310825/26857726-c25e-4cd4-a6cc-eb9db9eaa5dc)

![image](https://github.com/humhub/wiki/assets/23310825/2890f86d-cbcd-49e8-b575-251cdd5af509)

**Comment by luke-** [comment]
@marc-farre Great, looks  nice!
