### ISSUE TITLE
Use new Content Search for Wiki Search  

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#322]

**Comment by luke-** [comment]
Would be great, to use the new Content Search here to search Wiki Pages instead of using the Title only Search

![Image](https://github.com/humhub/wiki/assets/4736168/655d4cd0-b538-481b-9897-c7eadb84dbff)

**Comment by yurabakhtin** [comment]
@luke- @GillesCavelan Done in the PR https://github.com/humhub/wiki/pull/331.

**Comment by GillesCavelan** [comment]
Hi Yuriy, that's great. Do you know any way can we test it ?  Any idea about it to be implemented in a future HumHub's release ? 
Rgds, Gilles

**Comment by marc-farre** [comment]
@GillesCavelan Version 2.3.2, which has just been released, uses the new HumHub 1.16 search engine.
