### ISSUE TITLE
Make a wikipage public to non-registered users!

### ISSUE THREAD

**Issue by leopaula** [humhub/wiki#33]
I can't make public access to non-registered users in order for they read wiki page...It would be good if they (non-registered users) also could edit public page.

**Comment by wolfmarco** [comment]
It would be nice to be able to make a wikipage public to non-logged in users!

**Comment by ahmadazizi** [comment]
Wiki pages available to non-registered users is REALLY a wanted feature!

**Comment by buddh4** [comment]
We'll enhance some of the existing modules after the v1.2 release in january.

**Comment by Oremountainflorian** [comment]
It would be really cool if you could just give access to a single wiki page to non-logged-in users, not more that that :)

**Comment by luke-** [comment]
This would be more of a feature that would have to be implemented by the core for content in general.
