### ISSUE TITLE
Public pages doesn't appear on the overview

### ISSUE THREAD

**Issue by marc-farre** [humhub/wiki#334]
E.g., if I am not a member of [the Hosting space](https://community.humhub.com/s/hosting), I can see the wiki pages in the stream, but not in the wiki overview:

![image](https://github.com/humhub/wiki/assets/23310825/535889d7-4626-4126-a6d8-5acaaf52ca6b)

![image](https://github.com/humhub/wiki/assets/23310825/7c788fb5-0678-4884-bb85-7f104a47c469)

**Comment by yurabakhtin** [comment]
@marc-farre I see the parent page [Homepage](https://community.humhub.com/s/hosting/wiki/72/Homepage) is not public, so all children pages of the page cannot be listed under the hidden parent page. If you open the children page "[Jitsi Meet servers](https://community.humhub.com/s/hosting/wiki/247/Jitsi+Meet+servers)" you can view it.

@luke- Do you think we should do something for such case?

**Comment by luke-** [comment]
Hmm, is the page displayed under "Last Edited"?

Looks a bit broken somehow, I'm afraid it's difficult to find a solution here.

**Comment by marc-farre** [comment]
@yurabakhtin thanks, that's true.
And the "List categories" page works well: https://community.humhub.com/s/hosting/wiki/overview/list-categories 

However, shouldn't we throw a “Not allowed” error when viewing a private page without being a member of the space, instead of a blank page?

**Comment by luke-** [comment]
@marc-farre 

> However, shouldn't we throw a “Not allowed” error when viewing a private page without being a member of the space, instead of a blank page?

Unfortunately I can't find the issue right now, but I would like to have a generic handling for such cases.

("You need to become member", "Access Denied", "You need to login", ...)

It should not be necessary to implement this at module level.

Unfortunately, it is complicated and we have not yet found a nice solution.

Related: https://github.com/humhub/humhub-internal/issues/295

**Comment by marc-farre** [comment]
To make things clearer, we have 3 different pages (sorry, I was unclear with this):
- Homepage: https://community.humhub.com/s/hosting/wiki/72/Homepage
- List categories: https://community.humhub.com/s/hosting/wiki/overview/list-categories
- Last Edited: https://community.humhub.com/s/hosting/wiki/overview/last-edited

"Homepage" is a content and can be private or public. If think that if it's private, we should have an "Access Denied".

"List categories" and "Last Edited" are not a content (no private/public status). So I agree with your behavior proposal, @yurabakhtin 

Also, maybe we could prevent having a child page public if the parent is private.

**Comment by luke-** [comment]
Thanks for the explanation @marc-farre !

What is the proposal of @yurabakhtin? Not sure I fully got it.

There is also the scenario that no Homepage defined. Can't we just assume that if it is "Private", but the user can only see "Public" content?

**Comment by yurabakhtin** [comment]
> "Homepage" is a content and can be private or public. If think that if it's private, we should have an "Access Denied".

@marc-farre Currently we display "Wiki page not found!" for all cases because we filter it by `WikiPage::find()->readable()`, but if need I think we can split and display "Access Denied" for case `!$page->content->canView()`.

> Also, maybe we could prevent having a child page public if the parent is private.

For this we need to update all children recursively to private when the parent is updated to private, I am not sure how it is normal if it was changed by mistake, because I don't think we should do the reverse action when the parent page is updated from privte to public. So at least we must display a warning about changing all children pages to private.

---

> What is the proposal of @yurabakhtin? Not sure I fully got it.

@luke- My proposal was not completed because I am not sure what solution is better.

For example, we have such pages:

- Page A (public)
  - Page B (private)
    - Page C (public)
      - Page D (private)
        - Page E (public)

If current user has no access to the private pages then display them as:

1st solution:

- Page A (public)
  - [Not allowed]
    - Page C (public)
      - [Not allowed]
        - Page E (public)

2nd solution:

- Page A (public)

Currently we have the 2nd solution, it is why the issue ticket was creted here.
We can keep it as is, but probably we need to display the "Access Denied" as @marc-farre suggested.

**Comment by luke-** [comment]
I would keep the second (currently existing solution) for now. It is really difficult to display a "tree" if just parts are visible to the user.
This case should also be rather rare.
I think Marc was primarily concerned with the "homepage". correct?

**Comment by yurabakhtin** [comment]
@luke- Ok, done in the commits https://github.com/humhub/humhub/pull/7094/commits/bd3b356b2f7e575fcd6fa75155a3aa1fd5d7e378, https://github.com/humhub/calendar/pull/492/commits/37a189cbab4f7b4d0448d6e6154dd7fd86ae8611.

**Comment by marc-farre** [comment]
> I think Marc was primarily concerned with the "homepage". correct?

Yes.

@yurabakhtin thanks for the commits!

**Comment by luke-** [comment]
@yurabakhtin Your commits are related to the Calendar Module, I'll hide it here :-)

**Comment by yurabakhtin** [comment]
@luke- Oh yes sorry 🤦

**Comment by yurabakhtin** [comment]
@luke- 

> I think Marc was primarily concerned with the "homepage". correct?

Please confirm if we need to display a separate message "Access Denied" for case if user really has no access instead of current "Wiki page not found!" which is displayed for all cases.

**Comment by luke-** [comment]
Hmm, not sure right now. What is meant with "Access Denied"?

To sum up the problem: Public pages of Private Parent Pages are not listed in the overview? 

We can either:

- Show such parent Private Pages non clickable (this will disclose the title)
- Don't show such Public pages in the tree list (current solution)
- ...

Or did I misunderstood something?

**Comment by marc-farre** [comment]
I think private should remain invisible, so current solution is fine.

After a better analysis of the issue (I should have done it before, sorry), I found out that clicking on the "Wiki" Space menu item displays a different page depending on the Space membership.

![image](https://github.com/humhub/wiki/assets/23310825/314cf161-1dbb-411e-8678-131a475d00e1)

- If I am a Space member, the "Homepage" is displayed
- If I'm not a Space member, the "List categories" page is displayed

This issue is about the latter case:

![image](https://github.com/humhub/wiki/assets/23310825/01608063-7752-4ebb-94f3-80283dc57427)

![image](https://github.com/humhub/wiki/assets/23310825/2d9faa03-f48f-4764-bf2c-e8d9c867c6ff)

What about the following idea?

**On the "List categories" and "Last Edited", if no page links are displayed, show a message such as: "No public wiki pages"**:

![image](https://github.com/humhub/wiki/assets/23310825/b54e4f0a-c1c9-4717-92a9-902e5a4fd68c)

Similar to an empty stream or grid.

**Comment by yurabakhtin** [comment]
> Hmm, not sure right now. What is meant with "Access Denied"?

@luke- [Here](https://github.com/humhub/wiki/blob/master/controllers/PageController.php#L60-L63) we have the code:

```php
        $page = WikiPage::find()
            ->contentContainer($this->contentContainer)
            ->readable()
            ->andWhere(['wiki_page.id' => $id])
            ->one();

        if (!$page) {
            throw new HttpException(404, 'Wiki page not found!');
        }
```

If we will remove the filter `->readable()` it may looks like this:

```php
        $page = WikiPage::find()
            ->contentContainer($this->contentContainer)
            ->andWhere(['wiki_page.id' => $id])
            ->one();

        if (!$page) {
            throw new HttpException(404, 'Wiki page not found!');
        }

        if (!$page->content->canView()) {
            throw new HttpException(404, 'Access Denied!');
        }
```

**Comment by luke-** [comment]
> > Hmm, not sure right now. What is meant with "Access Denied"?
> 
> @luke- [Here](https://github.com/humhub/wiki/blob/master/controllers/PageController.php#L60-L63) we have the code:
> 

@yurabakhtin Thanks for the example. I wouldn't change that for now. We also have the problem in other places and I would like to find a core solution here.

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub/pull/6005
