### ISSUE TITLE
Wiki new search engine finds wiki pages from other spaces

### ISSUE THREAD

**Issue by marc-farre** [humhub/wiki#344]
### What steps will reproduce the problem?

1. Create a wiki page in a space
2. Switch to another space, in the wiki module
3. Search for a keyword contained in the wiki page created in the other space

### What is the expected result?

The wiki page is not found.

### What do you get instead?

The wiki page is displayed in the search result.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1
| Wiki version   | 2.3.3

**Comment by yurabakhtin** [comment]
@luke- To fix that we need the core changes https://github.com/humhub/humhub/pull/7146 where I have replaced the property `SearchRequest->space` with `SearchRequest->contentContainer` and `SearchRequest->contentContainerClass`.

PR https://github.com/humhub/wiki/pull/346 for fix Wiki module.
