### ISSUE TITLE
Deleting a parent page should move the child pages to the root

### ISSUE THREAD

**Issue by marc-farre** [humhub/wiki#345]
### What steps will reproduce the problem?

1. Create a parent and a child wiki pages:
![image](https://github.com/user-attachments/assets/05c7cfb7-756b-46aa-8547-b18e71c9d043)
2. Delete the parent page

### What is the expected result?

- The Child page is not related to the parent page anymore
- It is displayed in the wiki list page

### What do you get instead?

The child page is not visible anymore in the wiki list page:
![image](https://github.com/user-attachments/assets/9f1c6b7b-3c2c-493f-a7dc-65ee44739f33)

But it is not deleted: if we know the URL, we can open it.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.1
| Wiki version   | 2.3.3

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Fixed https://github.com/humhub/wiki/pull/347.
