### ISSUE TITLE
Improvement: Ability to nest wiki pages

### ISSUE THREAD

**Issue by rebeccapowell** [humhub/wiki#36]
It would be nice to nest pages (i.e. set a parent page), then at the bottom of each wiki page, a list of the child pages would be listed.

A sub menu could appear on the left hand menu as well (bonus feature).

**Comment by 3ruce** [comment]
+1

**Comment by jmvandamme** [comment]
+1

**Comment by WizarDave** [comment]
Temporary workaround?
Use a regular link to "child" pages.
*Create a list if need be.
Could be a downside that they would still be listed. Some might want child pages to not be in the main list.
Structured wiki's would be a nice addition...

**Comment by liqorice** [comment]
+1

**Comment by victor-moreno** [comment]
+1

**Comment by mtcoliveira** [comment]
+1

**Comment by pingadi** [comment]
+1
