### ISSUE TITLE
Long texts silently truncated

### ISSUE THREAD

**Issue by yrosner** [humhub/wiki#37]
_wiki_page_revision.content_ is defined as _TEXT_.
In MySQL _TEXT_ is limited to a maximum of 64kb. 
If strict mode in MySQL isn't activated the page content is silently truncated if larger than 64k.

**Comment by elbotho** [comment]
Thank you for the detailed issue, it helped me to fix it for me 👍

**Comment by luke-** [comment]
Was changed zu mediumtext;
