### ISSUE TITLE
Content lost on account deletion

### ISSUE THREAD

**Issue by alexryans** [humhub/wiki#42]
I notice that when a user is deleted from HumHub, all their wiki articles are removed.

To me, this seems like a serious flaw, as when used in an industry setting, employees leave or more on and it is impractical and potentially dangerous to keep their user account on HumHub. Is there some way to potentially have an option to transfer a user's wiki articles to another owner or, failing that, just leave all the wiki articles untouched when a user is deleted?

**Comment by buddha87** [comment]
Instead of deleting the user you also can deactivate his account under edit user, but you are right the content should not be lost when deleting auser. We plan to just hide the users when "delted" instead of removing its content in a future version. Thanks.

**Comment by 001101** [comment]
But what if the user deletes itself? 
As a admin I can not disable that, which is good and bad, in this case it is very bad.

**Comment by luke-** [comment]
Should be fixed with user soft delete
