### ISSUE TITLE
Add Print function

### ISSUE THREAD

**Issue by liqorice** [humhub/wiki#48]
### Feature request: Add print function to Wiki module

Like to request a function where we can `print`, `convert` or `save` all contents of the **wiki module** as a `PDF` or printed document.

Currently, to do such a thing, we'd have to click on each link and sub link, manually print/save page and then proceed to the next.

We run multiple projects and separate wiki's and access rights for each, sometimes we need to provide an external resource access to information for that project, but we couldn't provide them complete access to our internal system, so  we'd like to be able to extract that data and give it to them as a convenient document file (PDF/WORD etc) or print out.

**Comment by funkycram** [comment]
I have written a very small javascript script to add at the end of the `view/page/view.php` file (can be in the theme) to print the current page easily :

```
<script type="text/javascript">
    $('.wiki-menu >ul.nav').prepend('<li><a id="print-wiki-page" href="#"><i class="fa fa-print print"></i> Imprimer</a></li>');

    function printWikiPage()
    {
       var titleToPrint = $('.wiki-content >h1');
       var contentToPrint = $('.wiki-content >.markdown-render >.markdown-render');
       newWin= window.open("");
       newWin.document.write('<h1>' + titleToPrint.text() + '</h1>' + contentToPrint.html());
       newWin.print();
       newWin.close();
    }

    $('#print-wiki-page').on('click',function(){
       printWikiPage();
    })    
</script>
```

**Comment by gerhardbeck** [comment]
@funkycram Sorry I have to ask but in which file (exact path) to add the javascript? Don't have a `view/page/view.php` in my theme folder.
Thanks

**Comment by funkycram** [comment]
> @funkycram Sorry I have to ask but in which file (exact path) to add the javascript? Don't have a `view/page/view.php` in my theme folder.
> Thanks

https://github.com/humhub/humhub-modules-wiki/blob/master/views/page/view.php

**Comment by gerhardbeck** [comment]
Thanks. thought it, but the /view**s**/page... was irritating me.
I added it after
`...     <?= WikiMenu::widget(['page' => $page, 'revision' => $revision]) ?>

        </div>
    </div>
</div>`

but can notice no difference

**Comment by funkycram** [comment]
You're right, this code was working for an old Humhub version.
Try this one:
```
    $('.wiki-menu ul.nav').prepend('<li><a id="print-wiki-page" href="#"><i class="fa fa-print print"></i> Print this page</a></li>');

    function printWikiPage()
    {
       var titleToPrint = $('.wiki-content >h1');
       var contentToPrint = $('.wiki-content #wiki-page-richtext');
       newWin= window.open('');
       newWin.document.write('<html><head></head><body><h1>' + titleToPrint.text() + '</h1>' + contentToPrint.html() + '<script type="text/javascript">window.print();</script></body></html>');
       newWin.document.close(); //missing code
       newWin.print();
       newWin.close(); // In some browsers window is closed before printing dialog is closed...
    }

    $('#print-wiki-page').on('click',function(){
       printWikiPage();
    })   
```

**Comment by gerhardbeck** [comment]
Well, this one shows an effect but not intented:
When clicking on a wiki page it starts the print dialogue

https://user-images.githubusercontent.com/41069802/103172923-5b892000-4857-11eb-84a0-cffed2248382.mp4

I just added it at the end

**Comment by luke-** [comment]
https://github.com/humhub/wiki/issues/62
