### ISSUE TITLE
Add public/private pages

### ISSUE THREAD

**Issue by luke-** [humhub/wiki#6]
How to handle this?
- Allow only public/private per wiki or page?

If per page - what happens with links without permissions?

**Comment by Oremountainflorian** [comment]
@luke- Is there any way to share single wiki pages without permitting further access to space menu, top navigation bar, other wiki pages, …? Would be super useful for as we often would like to share minutes and instructions with external partners. Thanks a lot!

**Comment by buddh4** [comment]
We could think about implementing share links similar to onlyoffice.

**Comment by Oremountainflorian** [comment]
> 
> 
> We could think about implementing share links similar to onlyoffice.

This would be a major improvement for the HumHub Wiki! 

Another idea: Share link for whole wiki of spaces and share links for categories within the wiki without any further permissions to the person having the link.
