### ISSUE TITLE
Enhancement UI: Permalink for wiki page

### ISSUE THREAD

**Issue by githubjeka** [humhub/wiki#61]
![image](https://cloud.githubusercontent.com/assets/874234/26713134/ac685eac-4773-11e7-9179-34e189c5a949.png)

If go to by link then

![image](https://cloud.githubusercontent.com/assets/874234/26713183/e431ddfe-4773-11e7-8288-37ae96a7b66d.png)

That not get on the wiki page, it's review of wiki page, which requires one more click.

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
