### ISSUE TITLE
Add Print Version

### ISSUE THREAD

**Issue by buddh4** [humhub/wiki#62]

**Comment by gerhardbeck** [comment]
Isn't it connected to #89 ?

**Comment by Oremountainflorian** [comment]
@gerhardbeck No, isn't the case yet if I'm right. Please upvote #89. This could then be closed I guess

**Comment by gerhardbeck** [comment]
> @gerhardbeck No, isn't the case yet if I'm right. Please upvote #89. This could then be closed I guess

I guess so, too. I already upvoted it

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/183:

<img width="1755" alt="print_wiki_page" src="https://user-images.githubusercontent.com/6995524/122897063-51516580-d352-11eb-954e-d865931b3fcd.png">

**Comment by luke-** [comment]
@yurabakhtin Looks great!

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/wiki/pull/184:

<img width="1484" alt="print_without_comments" src="https://user-images.githubusercontent.com/6995524/123039596-18b99680-d3fb-11eb-89b0-d1548910232e.png">
