### ISSUE TITLE
[enhancement] Add a better visual editor

### ISSUE THREAD

**Issue by warshell** [humhub/wiki#63]
I mean cmon, its too soft for 2k17.)
Im dreaming of copy html images , links  as it is, like in dopbox paper or evernote is the best examples
even a wikipedia has a new fresh editor.

thanks

**Comment by devcline** [comment]
https://github.com/dropbox/hackpad 

 we need a WUI editor for Markdown

**Comment by buddh4** [comment]
We'll switch our richtext to [ProseMirror](https://prosemirror.net/) in v1.3 and in a next step adapt this editor in the wiki module etc. The editor is actively developed, seems to be very clean and extensible and also supports collaborative editing.

Hackpad seems not to be maintained anymore, but thanks for the suggestion.

**Comment by paviro** [comment]
I'd would also be great if it would be possible to show a none WYSIWYG version of the page. Coping tables etc. are a pain in the visual editor.

**Comment by Oremountainflorian** [comment]
ProseMirror looks really good as it tries to close the gap beetween markdown and WYSIWYG and also allows collaborative working... 

This would also make the Etherpad integration more or less obsolute... Collaborative working is super important, but of course it doesn't look good... But if we could work on good looking wiki pages at the same time. Hell yeah! :dagger:

**Comment by buddh4** [comment]
@Oremountainflorian feel free to make suggestions for better wiki styles. 

And note that the HumHub richtext is already based on prosemirror, the collaborative editing is not part of prosemirror by default and needs to be integrated first.

**Comment by devcline** [comment]
> @Oremountainflorian feel free to make suggestions for better wiki styles.
> 
> And note that the HumHub richtext is already based on prosemirror, the collaborative editing is not part of prosemirror by default and needs to be integrated first.

As commiting for me its a bit pain, i will post here my css fixes

This hack (font-weight: 500;) permits a user define a bold himself in a header, so he can write a simple (not bolded) text too
```
[data-ui-markdown] table th, [data-ui-richtext] table th {
    font-size: 13px;
    font-weight: 500;
    color: #555;
    background-color: #f7f7f7;
}
```

Aligned text in the row to the top and not to the center.
```
[data-ui-markdown] table tr, [data-ui-richtext] table tr {
    vertical-align: top;
}
```

This makes rows aligned to the center
```
[data-ui-markdown] table, [data-ui-richtext] table {
    width: 100%;
    table-layout: fixed;
}
```

**Comment by warshell** [comment]
The [Quilljs Editor ](https://quilljs.com/)is really nice one alternative
