### ISSUE TITLE
Single quotation mark doesn't work in links

### ISSUE THREAD

**Issue by funkycram** [humhub/wiki#68]
If I use a ' char in a link like this :
![image](https://user-images.githubusercontent.com/23310825/31315394-36085a00-ac18-11e7-8439-88a3e6b4605f.png)

The link will be :
![image](https://user-images.githubusercontent.com/23310825/31315413-746a776a-ac18-11e7-9666-8e5dc6703334.png)

Which is transformed by the navigator to `/wiki/page/view?title=my+internal+page+%26%23039%3B+link` instead of `/wiki/page/view?title=my+internal+page+'+link`

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
