### ISSUE TITLE
Extended Wiki features

### ISSUE THREAD

**Issue by gituser317** [humhub/wiki#69]
Hello,

we are using the wiki module in our company and loving it, but we are missing two features.
The first is to make parent and child sites in Wiki and the other one is to make table of contents.
Is there a way to do it or a feature that is planned in the future?

Thank you for your answer!

**Comment by buddh4** [comment]
yes its definetly planned to rework the wiki, a wiki hierarchy is on the todo list, but I can't tell you when, if you need a feature as fast as possible please contact info@humhub.com

**Comment by cellarcode** [comment]
Hello there, is there any kind of documentation or list of features for this module yet?

**Comment by gueeme** [comment]
Hello, are you predicting when this feature will be released?

**Comment by Oremountainflorian** [comment]
We also use the wiki within our group and basically we're really happy about it! But as the others said, parent and child sites in the wiki would be awesome!

**Comment by JK742020** [comment]
Same to me if parent and child means more levels of hierarchy. This would be really great!

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
