### ISSUE TITLE
'>' inside Code block is converted in Markdown

### ISSUE THREAD

**Issue by acsfer** [humhub/wiki#76]
If you type **Word --> Word** inside a code block in Markdown, it should became:

`Word --> Word`

instead, it becomes:

`Word --&gt; Word`

Probably related to https://github.com/humhub/humhub-modules-wiki/issues/24

Is this a problem with this module or with @cebe https://github.com/cebe/markdown parser?

**Comment by cebe** [comment]
`cebe/markdown` will convert `>` to `&gt;` to be valid HTML, if the `&gt;` then gets encoded again that should be a problem of Humhub.

See http://markdown.cebe.cc/try?flavor=default&text=Word+--%3E+Word

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
