### ISSUE TITLE
User permissions for applying categories

### ISSUE THREAD

**Issue by v4bene** [humhub/wiki#83]
Hello. Shouldn't members be able to select a category when they create a wiki page?
Or is there an option for that already?

**Comment by iello** [comment]
First create a wiki category by checking "Is category". Then users will be able to select it when creating a page.

**Comment by v4bene** [comment]
For normal users in our humub (wiki module 1.2.2) there is no dropdown menu to select the categories when creating a wiki page. Although there are categories and the admin can select them.

![grafik](https://user-images.githubusercontent.com/43067371/45281246-8d83e600-b4d7-11e8-9490-8bff6e41aab2.png)

Since we are still testing humhub with just a few users I added USERGROUP_MEMBER to AdministerPages.php as a first workaround.

**Comment by v4bene** [comment]
seems like selecting categories is only intended for users with administration rights:
in /views/page/edit.php
```
<?php if ($canAdminister): ?>
            <?= $form->field($page, 'is_home')->checkbox(); ?>
            <?= $form->field($page, 'admin_only')->checkbox(); ?>
            <?= $form->field($page, 'is_category')->checkbox(); ?>
            <?php if ($hasCategories): ?>
                        <?= $form->field($page, 'parent_page_id')->dropDownList($page->getCategoryList()); ?>
            <?php endif; ?>
<?php endif; ?>
```

**Comment by buddh4** [comment]
I think the dropdown should at least be available, when you are the author of this page.

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
