### ISSUE TITLE
Permalink do not show the correct link 

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub/wiki#84]
when clicking in the parmalink it shows wrong link. It seems so it starts on the top and going down the list one by one. I have attached some pictures of my test Wiki with three articles in to demonstrate the problem. I have done this in humhub 1.2.5 and version 1.1.10 of Wiki module.

![image](https://user-images.githubusercontent.com/30318362/45954594-b8108b80-c00d-11e8-9e1f-acf0358f9150.png)

![image](https://user-images.githubusercontent.com/30318362/45954604-bfd03000-c00d-11e8-9f02-57d5350d9839.png)

**Comment by buddh4** [comment]
Does it link to the wrong content or do you just expect the cleaner wiki link?

**Comment by arnfinnkristensen** [comment]
Hi,

The system gives me the wrong link.

Arnfinn H. Kristensen

Fra: buddh4 <notifications@github.com>
Sendt: tirsdag 9. oktober 2018 14:52
Til: humhub/humhub-modules-wiki <humhub-modules-wiki@noreply.github.com>
Kopi: arnfinnkristensen <arnfinnkristensen@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [humhub/humhub-modules-wiki] Permalink do not show the correct link (#84)


Does it link to the wrong content or do you just expect the cleaner wiki link?

**Comment by buddh4** [comment]
Sorry I don't know what you mean with "wrong link", what happens if you access the url, do you get a 404 error? The url shown in your image is the default permalink url format used for all content types.

**Comment by arnfinnkristensen** [comment]
Ok. I Get a link that is valide but it show the wrong content.

Arnfinn.

Sendt fra min iPhone

9. okt. 2018 kl. 20:02 skrev buddh4 <notifications@github.com<mailto:notifications@github.com>>:


Sorry I don't know what you mean with "wrong link", what happens if you access the url, do you get a 404 error? The url shown in your image is the default permalink url format used for all content types.

**Comment by buddh4** [comment]
Thanks, now I understand. I'll have a look, unfortunately you are using a rather old module version, but I assume you currently can't update your HumHub core version. The Wiki Module was almost completely rewritten for HumHub 1.3.

**Comment by arnfinnkristensen** [comment]
Okay,

We are in progress to update to 1.3.4 so maybe I shall test it there first.

Arnfinn H. Kristensen

Fra: buddh4 <notifications@github.com>
Sendt: tirsdag 9. oktober 2018 20:56
Til: humhub/humhub-modules-wiki <humhub-modules-wiki@noreply.github.com>
Kopi: arnfinnkristensen <arnfinnkristensen@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [humhub/humhub-modules-wiki] Permalink do not show the correct link (#84)


Thanks, now I understand. I'll have a look, unfortunately you are using a rather old module version, but I assume you currently can't update your HumHub core version. The Wiki Module was almost completely rewritten for HumHub 1.3.

**Comment by luke-** [comment]
Should be fixed. If not please reopen it.
