### ISSUE TITLE
Sidebar is broken on scroll

### ISSUE THREAD

**Issue by Felli** [humhub/wiki#92]
As you'll see in the image below when you scroll the sidebar now breaks the page on scroll and doesn't show all options on large wikis such as the ones created in the community site.
![10d0058b87de8d1d80627623f6c4c861](https://user-images.githubusercontent.com/2011633/55527011-4c1a7a00-5665-11e9-9275-1a93d6837924.gif)

**Comment by Oremountainflorian** [comment]
I have the same problem... If you're writing a long wiki entry, the lower chapters aren't shown in the page index as it isn't possible to scroll down. Page index always jumps up again as you scroll down. 

Another thing is that the Page index panel gets stuck 3 lines below the upper border (as you can see in the image below). 

I'd also really appreciate if you could fix that! 

![image](https://user-images.githubusercontent.com/44228345/77910392-57f84680-728f-11ea-93e3-bc1e9ead2aeb.png)

**Comment by MasterMindNET** [comment]
Hello, @Oremountainflorian!

Here is the solution for this issue:
https://github.com/humhub/humhub-modules-wiki/pull/134
So after the `134` PR  is merged, I believe it would be in the next tested and released in the nearest feature.

**Comment by luke-** [comment]
Should be fiexed here: https://github.com/humhub/wiki/commit/8607437274f053275218345f651abb2ee098f35f
