### ISSUE TITLE
Create global wiki outside of spaces

### ISSUE THREAD

**Issue by Ninos** [humhub/wiki#93]
Hey there,

we need the functionality to create wiki pages outside of the spaces, so wiki is globally available for all users. Is there a possibility?

Kindest regards

**Comment by Ace2213** [comment]
I created a space for this and made it public. Once Humhub provides the ability to hide the member widget, I'll make it default. For now, I'll try using the auto follow module to make everyone follow it without joining, which should make it appear in their space menu.

**Comment by buddh4** [comment]
I think in a first version, there should be a global overview of all wikis with the spaces as root.

**Comment by devcline** [comment]
Temp solution: now you can create a custom formated page and link to all other wikis.

**Comment by luke-** [comment]
There are no plans to make wiki pages available outside Spaces/Users.

However, there may be a summary view in the future.
